apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  labels:
    agent: Create an agent that generates poems from Donald T
    environment: staging
    managed-by: caminu
  name: Create an agent that generates poems from Donald T-staging
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '10'
        autoscaling.knative.dev/minScale: '0'
        run.googleapis.com/cpu-throttling: 'false'
    spec:
      containers:
      - env:
        - name: ENVIRONMENT
          value: staging
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              key: latest
              name: openai-api-key
        image: gcr.io/${PROJECT_ID}/Create an agent that generates poems from Donald
          T:${IMAGE_TAG}
        ports:
        - containerPort: 8080
          name: http1
        resources:
          limits:
            cpu: '1'
            memory: 512Mi
      serviceAccountName: Create an agent that generates poems from Donald T-sa
